# Generated by Django 3.2.3 on 2021-06-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_name',
            new_name='default_full_name',
        ),
    ]
