# Generated by Django 3.2.3 on 2021-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_these_changes', models.CharField(default='Default Styling', max_length=200)),
                ('small_banner_text', models.CharField(default='Welcome', max_length=200)),
                ('choose_background_color_class', models.CharField(choices=[('admin-bg-color__red', 'Red'), ('admin-bg-color__blue', 'Blue'), ('admin-bg-color__green', 'Green'), ('admin-bg-color__black', 'Black'), ('admin-bg-color__white', 'White')], default='Blue', max_length=30)),
                ('choose_text_color_class', models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Blue', max_length=30)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('header_icon_colors', models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Blue', max_length=30)),
                ('do_not_display', models.BooleanField(default=False, help_text='Check this box to hide this specific banner.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': 'Header Customisation',
            },
        ),
        migrations.CreateModel(
            name='HomePageCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_these_changes', models.CharField(default='Name This Styling...', max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_page_text', models.TextField(max_length=3500)),
                ('main_page_text_color', models.TextField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Pick a color')),
                ('button_text', models.CharField(default='Shop Now', max_length=15)),
                ('button_text_color', models.TextField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Pick a color')),
                ('button_background_color', models.CharField(choices=[('admin-bg-color__red', 'Red'), ('admin-bg-color__blue', 'Blue'), ('admin-bg-color__green', 'Green'), ('admin-bg-color__black', 'Black'), ('admin-bg-color__white', 'White')], default='Blue', max_length=30)),
                ('do_not_display', models.BooleanField(default=False, help_text='Check this box to hide this specific banner.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': 'Home Page Customisation',
            },
        ),
    ]
