# Generated by Django 3.2.3 on 2021-06-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercustomisation',
            old_name='header_text_colors',
            new_name='header_text_color',
        ),
    ]
