# Generated by Django 3.2.3 on 2021-06-20 20:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_productspagecustomisation_product_card_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagecustomisation',
            name='product_card_icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='product_card_font',
            field=models.CharField(default='', max_length=50),
        ),
    ]
