# Generated by Django 3.2.3 on 2021-06-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_productspagecustomisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headercustomisation',
            options={'verbose_name_plural': 'Header'},
        ),
        migrations.AlterModelOptions(
            name='homepagecustomisation',
            options={'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='productspagecustomisation',
            options={'verbose_name_plural': 'Products Page'},
        ),
        migrations.AddField(
            model_name='productspagecustomisation',
            name='product_card_font_color',
            field=models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='No Border', max_length=30),
        ),
    ]
