# Generated by Django 3.2.3 on 2021-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_auto_20210629_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercustomisation',
            name='header_icon_color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='header_text_color',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
