# Generated by Django 3.2.3 on 2021-06-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0003_auto_20210619_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercustomisation',
            old_name='name_these_changes',
            new_name='header_styling',
        ),
        migrations.RenameField(
            model_name='homepagecustomisation',
            old_name='name_these_changes',
            new_name='home_page_styling',
        ),
        migrations.RenameField(
            model_name='productspagecustomisation',
            old_name='name_these_changes',
            new_name='products_page_styling',
        ),
    ]
