# Generated by Django 3.2.3 on 2021-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0003_auto_20210630_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='add_to_bag_button_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='add_to_bag_button_text_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='keep_shopping_button_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='keep_shopping_button_text_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='product_page_background_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='products_page_text_color',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__right', 'Right'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__right', 'Right'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
    ]
