# Generated by Django 3.2.3 on 2021-06-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0003_auto_20210620_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='product_card_font',
        ),
    ]
