# Generated by Django 3.2.3 on 2021-06-28 10:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0004_auto_20210627_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSiteStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_site_styles', models.CharField(help_text='Give these global styles a name...', max_length=20)),
                ('base_background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('base_font_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('all_icon_colors', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
