# Generated by Django 3.2.3 on 2021-06-20 14:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0004_auto_20210619_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
