# Generated by Django 3.2.3 on 2021-06-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0004_remove_productspagecustomisation_product_card_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_text',
            field=models.CharField(default='Welcome', max_length=100),
        ),
    ]
