# Generated by Django 3.2.3 on 2021-07-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0005_auto_20210630_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitestyling',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='Check this box to hide this specific styling.', unique=True, verbose_name='Do not display'),
        ),
    ]
