# Generated by Django 3.2.3 on 2021-06-20 14:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0005_headercustomisation_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercustomisation',
            name='choose_background_color_class',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='choose_text_color_class',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='header_icon_colors',
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='header_icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='small_banner_background_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='small_banner_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
