# Generated by Django 3.2.3 on 2021-06-21 10:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0005_alter_headercustomisation_small_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='header_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
    ]
