# Generated by Django 3.2.3 on 2021-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0006_auto_20210627_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecustomisations',
            old_name='main_site_background',
            new_name='main_background_color',
        ),
        migrations.RenameField(
            model_name='sitecustomisations',
            old_name='page_title_colors',
            new_name='main_text_color',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
