# Generated by Django 3.2.3 on 2021-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0006_auto_20210628_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitestyling',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='Check this box to hide this specific styling.', verbose_name='Do not display'),
        ),
    ]
