# Generated by Django 3.2.3 on 2021-06-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0006_headercustomisation_header_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='Left'),
        ),
    ]
