# Generated by Django 3.2.3 on 2021-07-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0007_auto_20210716_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitestyling',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='Check this box to hide this specific styling.', verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='CHECK THIS BOX TO HIDE THIS SPECIFIC STYLING.', verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
