# Generated by Django 3.2.3 on 2021-06-20 14:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0007_headercustomisation_search_icon_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='search_icon_color',
            field=colorfield.fields.ColorField(default='#000', max_length=18),
        ),
    ]
