# Generated by Django 3.2.3 on 2021-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0009_alter_homepagecustomisation_main_page_text_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='CHECK THIS BOX TO HIDE THIS SPECIFIC STYLING.', verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='CHECK THIS BOX TO HIDE THIS SPECIFIC STYLING.', verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
