# Generated by Django 3.2.3 on 2021-06-20 15:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0009_auto_20210620_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='choose_border_color',
        ),
        migrations.AddField(
            model_name='productspagecustomisation',
            name='border_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='product_card_font_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
