# Generated by Django 3.2.3 on 2021-06-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0010_auto_20210620_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagecustomisation',
            name='add_border_to_product_cards',
            field=models.CharField(choices=[('add-border__1', '1'), ('add-border__2', '2'), ('add-border__3', '3'), ('add-border__4', '4'), ('add-border__5', '5'), ('no-border', 'No Border')], default='No Border', max_length=200),
        ),
    ]
