# Generated by Django 3.2.3 on 2021-06-20 15:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0011_productspagecustomisation_add_border_to_product_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='header_text_colors',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='search_icon_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='add_border_to_product_cards',
            field=models.CharField(choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='No Border', max_length=200),
        ),
    ]
