# Generated by Django 3.2.3 on 2021-06-27 15:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0011_auto_20210627_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagecustomisation',
            name='add_to_bag_button',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', help_text='**Product Display Page', max_length=18),
        ),
        migrations.AddField(
            model_name='productspagecustomisation',
            name='keep_shopping_button',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', help_text='**Product Display Page', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__right', 'Right'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__right', 'Right'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
    ]
