# Generated by Django 3.2.3 on 2021-06-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0012_auto_20210620_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text',
            field=models.TextField(max_length=350),
        ),
    ]
