# Generated by Django 3.2.3 on 2021-06-20 16:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0013_alter_homepagecustomisation_main_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='search_icon_background_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
