# Generated by Django 3.2.3 on 2021-06-24 10:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0014_auto_20210622_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagecustomisation',
            name='product_quantity_buttons',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', help_text='Product Display Page', max_length=18),
        ),
    ]
