# Generated by Django 3.2.3 on 2021-06-20 16:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0014_alter_headercustomisation_search_icon_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='header_icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='header_text_colors',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='search_icon_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='search_icon_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='button_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='border_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='product_card_font_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
    ]
