# Generated by Django 3.2.3 on 2021-06-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0015_auto_20210620_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercustomisation',
            name='header_icon_color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='header_text_colors',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='search_icon_background_color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='search_icon_color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='small_banner_background_color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='small_banner_text_color',
        ),
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='button_background_color',
        ),
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='main_page_text_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='productspagecustomisation',
            name='product_card_font_color',
        ),
    ]
