# Generated by Django 3.2.3 on 2021-06-24 10:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0015_productspagecustomisation_product_quantity_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspagecustomisation',
            name='category_tag_background',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='**Check this box to hide the specific styling.', verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='product_quantity_buttons',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', help_text='**Product Display Page', max_length=18),
        ),
    ]
