# Generated by Django 3.2.3 on 2021-06-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0017_auto_20210620_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='add_border_to_product_cards',
            field=models.TextField(choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='No Border', max_length=200),
        ),
    ]
