# Generated by Django 3.2.3 on 2021-06-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0018_alter_productspagecustomisation_add_border_to_product_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspagecustomisation',
            old_name='add_border_to_product_cards',
            new_name='add_card_border',
        ),
    ]
