# Generated by Django 3.2.3 on 2021-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0020_auto_20210620_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text',
            field=models.TextField(max_length=35),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='add_card_border',
            field=models.TextField(choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='No Border', max_length=35),
        ),
    ]
