# Generated by Django 3.2.3 on 2021-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0021_auto_20210620_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_text',
            field=models.CharField(default='Welcome', max_length=20),
        ),
        migrations.AlterField(
            model_name='productspagecustomisation',
            name='add_card_border',
            field=models.TextField(choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='No Border'),
        ),
    ]
