# Generated by Django 3.2.3 on 2021-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title_for_backend', models.CharField(default='image title...', max_length=35)),
                ('image', models.ImageField(upload_to='media')),
                ('main_page_text', models.TextField(max_length=3500)),
            ],
        ),
    ]
