# Generated by Django 3.2.3 on 2021-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepagecustomisation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_banner_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepagecustomisation',
            options={'verbose_name_plural': 'Home Page Customisation'},
        ),
    ]
