# Generated by Django 3.2.3 on 2021-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210614_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebackgroundimage',
            name='title',
            field=models.TextField(default='Some text'),
        ),
    ]
