# Generated by Django 3.2.3 on 2021-06-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210616_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_text',
            field=models.TextField(max_length=200),
        ),
    ]
