# Generated by Django 3.2.3 on 2021-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepagebackgroundimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebackgroundimage',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
