# Generated by Django 3.2.3 on 2021-06-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepagebackgroundimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagebackgroundimage',
            old_name='title',
            new_name='image_title',
        ),
    ]
