# Generated by Django 3.2.3 on 2021-06-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagecustomisation_small_banner_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderCustomisation',
        ),
    ]
