# Generated by Django 3.2.3 on 2021-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_title_homepagebackgroundimage_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebackgroundimage',
            name='image_title',
            field=models.CharField(max_length=25),
        ),
    ]
