# Generated by Django 3.2.3 on 2021-06-14 12:14

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepagebackgroundimage_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebackgroundimage',
            name='image_title',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
