# Generated by Django 3.2.3 on 2021-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_headercustomisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_text',
            field=models.CharField(default='Welcome', max_length=200),
        ),
    ]
