# Generated by Django 3.2.3 on 2021-06-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_headercustomisation_small_banner_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='small_banner_text',
        ),
    ]
