# Generated by Django 3.2.3 on 2021-06-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepagebackgroundimage_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageBackgroundImage',
            new_name='HomePageCustomisation',
        ),
    ]
