# Generated by Django 3.2.3 on 2021-06-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_homepagebackgroundimage_homepagecustomisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecustomisation',
            old_name='image_title',
            new_name='main_page_text',
        ),
    ]
