# Generated by Django 3.2.3 on 2021-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepagecustomisation_small_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='button_text',
            field=models.TextField(default='Shop Now', max_length=15),
        ),
    ]
