# Generated by Django 3.2.3 on 2021-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_image_title_homepagecustomisation_main_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='image_title_for_backend',
            field=models.CharField(default='image title...', max_length=35),
        ),
    ]
