# Generated by Django 3.2.3 on 2021-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_headercustomisation_choose_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='choose_color_class',
            field=models.CharField(default='Blue', max_length=30),
        ),
    ]
