# Generated by Django 3.2.3 on 2021-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_headercustomisation_choose_color_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercustomisation',
            old_name='choose_color_class',
            new_name='choose_background_color_class',
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='choose_text_color_class',
            field=models.CharField(choices=[('admin-bg-color__red', 'Red'), ('admin-bg-color__blue', 'Blue'), ('admin-bg-color__green', 'Green'), ('admin-bg-color__black', 'Black'), ('admin-bg-color__white', 'White')], default='Blue', max_length=30),
        ),
    ]
