# Generated by Django 3.2.3 on 2021-06-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210617_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='choose_text_color_class',
            field=models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Blue', max_length=30),
        ),
    ]
