# Generated by Django 3.2.3 on 2021-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_headercustomisation_name_these_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='do_not_display',
            field=models.BooleanField(default=True, verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=15),
        ),
    ]
