# Generated by Django 3.2.3 on 2021-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210617_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='Check this box to hide this specific banner.', verbose_name='Do not display'),
        ),
    ]
