# Generated by Django 3.2.3 on 2021-06-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_headercustomisation_do_not_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecustomisation',
            old_name='image_title_for_backend',
            new_name='name_these_changes',
        ),
    ]
