# Generated by Django 3.2.3 on 2021-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_image_title_for_backend_homepagecustomisation_name_these_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='main_page_text_color',
            field=models.TextField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Pick a color'),
        ),
    ]
