# Generated by Django 3.2.3 on 2021-06-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homepagecustomisation_do_not_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='do_not_display',
        ),
    ]
