# Generated by Django 3.2.3 on 2021-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_homepagecustomisation_do_not_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='button_background_color',
            field=models.CharField(choices=[('admin-bg-color__red', 'Red'), ('admin-bg-color__blue', 'Blue'), ('admin-bg-color__green', 'Green'), ('admin-bg-color__black', 'Black'), ('admin-bg-color__white', 'White')], default='Blue', max_length=30),
        ),
        migrations.AddField(
            model_name='homepagecustomisation',
            name='button_text_color',
            field=models.TextField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Pick a color'),
        ),
    ]
