# Generated by Django 3.2.3 on 2021-06-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210617_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
