# Generated by Django 3.2.3 on 2021-06-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_headercustomisation_header_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='Check this box to hide this specific banner.', verbose_name='Do not display'),
        ),
        migrations.AlterField(
            model_name='headercustomisation',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
