# Generated by Django 3.2.3 on 2021-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210618_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='my_account_icon_color',
            field=models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Blue', max_length=30),
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='shopping_bag_icon_color',
            field=models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Blue', max_length=30),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='name_these_changes',
            field=models.CharField(default='Name This Styling...', max_length=35),
        ),
    ]
