# Generated by Django 3.2.3 on 2021-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210618_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercustomisation',
            name='my_account_icon_color',
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='my_account_icon',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
