# Generated by Django 3.2.3 on 2021-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210618_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='shopping_bag_icon_color',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
