# Generated by Django 3.2.3 on 2021-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_headercustomisation_shopping_bag_icon_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercustomisation',
            old_name='shopping_bag_icon_color',
            new_name='shopping_bag_icon',
        ),
    ]
