# Generated by Django 3.2.3 on 2021-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_shopping_bag_icon_color_headercustomisation_shopping_bag_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercustomisation',
            old_name='my_account_icon',
            new_name='shopping_bag_icon_color',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='shopping_bag_icon',
        ),
        migrations.AddField(
            model_name='headercustomisation',
            name='my_account_icon_color',
            field=models.CharField(choices=[('admin-color__red', 'Red'), ('admin-color__blue', 'Blue'), ('admin-color__green', 'Green'), ('admin-color__black', 'Black'), ('admin-color__white', 'White')], default='Blue', max_length=30),
        ),
    ]
