# Generated by Django 3.2.3 on 2021-06-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210618_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headercustomisation',
            old_name='my_account_icon_color',
            new_name='header_icon_colors',
        ),
        migrations.RemoveField(
            model_name='headercustomisation',
            name='shopping_bag_icon_color',
        ),
    ]
