# Generated by Django 3.2.3 on 2021-06-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210618_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderCustomisation',
        ),
    ]
