# Generated by Django 3.2.3 on 2021-06-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_delete_headercustomisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCustomisation',
        ),
    ]
